name: sigmafmt

on: [workflow_dispatch, push]

jobs:
  build:
    name: sigmafmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out rules
        uses: actions/checkout@v2
      - name: sigmafmt
        uses: bradleyjkemp/sigmafmt/github-action@github-action
