name: sigmafmt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: sigmafmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out rules
        uses: actions/checkout@v2
      - name: sigmafmt
        uses: bradleyjkemp/sigmafmt/github-action@gh-action-comment-pr
        with:
          path: 'macos'
